version: '3'

services:
  web:
    build: .
    ports:
      - "9292:9292"
    depends_on:
      - rabbitmq

  workers:
    build: .
    volumes:
      - .:/sneakers
    depends_on:
      - rabbitmq
    command: sneakers work ImageProcessorWorker --require ./workers/image_processor_worker.rb
    environment:
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672

  rabbitmq:
    image: rabbitmq:latest
    ports: 
        - "15672:15672"
        - "5672:5672"


